[package]
name = "wabash_db"
version = "0.1.0"
authors = ["Brandon Harrell <branh0913@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde="1.0.104"
serde_json="1.0.48"
